### ISSUE TITLE
Flash Nokia 3.2

### ISSUE THREAD

**Issue by sveip** [ac973k/NokiaManager#1]
Hi, I tried flashing this with the bat-script, but I get an error that remote auth doesn't pass. adb seems to be able to send the img fine though to the phone.

I'm using the latest drivers from here: https://developer.android.com/studio/run/win-usb

Any advice?

**Comment by ac973k** [comment]
Hi!
Restarted adb server:
adb kill-server
adb start-server
Reconnect the device

**Comment by sveip** [comment]
Thank you for the response!

I think that adb can reach the phone ok, but I suspect the bootloader is locked somehow. Is there a adb or fasboot cmd I have to run first to unlock the bootloader to allow flashing?

**Comment by ac973k** [comment]
Yes sure. There are commands to unlock the bootloader:
fastboot flashing get_unlock_ability
fastboot oem unlock-go
The Userdata will be erased.

**Comment by sveip** [comment]
Thanks! Is it possible to re-lock the bootloader?

**Comment by ac973k** [comment]
Yes, you can lock the bootloader again, but only with stock firmware, without any changes.
fastboot oem lock-go

**Comment by sveip** [comment]
Thanks, are the firmwares you have under releases in this repo stock? I
wasn't aware of any custom roms for the Nokia 3.2. My main concern is that
the A11 Rom from Nokia is buggy, no storage is broken, among other things.
This is the reason I want to revert to A10.

ons. 9. nov. 2022 kl. 19:37 skrev Danilka Terentyev <
***@***.***>:

**Comment by ac973k** [comment]
Yes =).
Android 9: https://github.com/ac973k/NokiaManager/releases/tag/Android9
Android 10: https://github.com/ac973k/NokiaManager/releases/tag/Android10
